version: '2'

services:
    db:
        image: klaemo/couchdb:2.0-dev
        ports:
            - "15984:15984"

    php:
        build: docker/php-fpm
        volumes:
            - ./:/app
        working_dir: /app
        network_mode: bridge
        ports:
            - "9000:9000"
