version: '2'

services:
    db:
        build: docker/couchdb
        ports:
            - "5984:5984"

    php:
        build: docker/php-fpm
        volumes:
            - ./:/app
        working_dir: /app
        network_mode: bridge
        ports:
            - "9000:9000"
